#尝试使用zuul作为网关，不集成webflux

server:
  port: 10010
  servlet:
    session:
      persistent: true
      timeout: 36000  #session 过期时间
#      cookie:
#        max-age: 7d
spring:
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: immediate
  application:
    name: spring-project-zuul
  redis:
    host: localhost #redis服务器地址
    port: 6379 #端口号
    database: 1
    timeout: 36000 #redis 过期时间

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/




#zuul 网关路由代理
#=参考 https://blog.csdn.net/s573626822/article/details/83180567
zuul:
  ignored-services: "*"
  ignored-headers:  #全局忽略请求头

  routes:

    hello: #可自定义名称
      path: /hello/**
      url: http://localhost:10001/ #可以是地址


    test:
      path: /test/**
      sensitiveHeaders: test #能够过滤请求头，不传入下游
      serviceId: spring-project-test  #可以是eureka上注册的name

    thymeleaf:
      path: /th/**
      serviceId: spring-project-thymeleaf






